language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script: 
  - composer.phar install
  - app/console cache:clear --no-warmup

script: 
  - phpunit -c app/

notifications:
  email:
    recipients: tetsuwo.oishi+travis-ci@gmail.com
    on_success: always # [always|never|change]
    on_failure: always # [always|never|change]
